name: Pylint

on:
  push:
    paths:
    - 'taky/**'
    - 'tests/**'
    - 'pyproject.toml'
    - 'uv.lock'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      pylint-score: ${{ steps.pylint.outputs.score }}
      cov-pct: ${{ steps.tests.outputs.cov-pct }}

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Install uv
      uses: astral-sh/setup-uv@v10.1.0
      with:
        enable-cache: true
    - id: setup-python
      name: Set up Python
      run: uv python install
    - id: setup-deps
      name: Install dependencies
      run: uv sync --locked
    - id: pylint
      name: Analyzing the code with pylint
      run: |
        SCORE=$(uv run python -c "from pylint.lint import Run; ret = Run(['taky'], do_exit=False); print('%.2f' % ret.linter.stats.global_note)")
        echo "score=${SCORE}" >> "$GITHUB_OUTPUT"
    - id: tests
      name: Running unit tests, generating coverage
      run: |
        uv run coverage run -m unittest discover || true
        COV_PCT=$(uv run coverage report | awk '/TOTAL/{ print $NF }')
        echo "cov-pct=${COV_PCT}" >> "$GITHUB_OUTPUT"
  badges:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - id: shieldsio-pylint
      name: Create the Pylint Badge
      uses: schneegans/dynamic-badges-action@v1.9.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: b8b273c056ed05901cfc671070e875ed
        filename: taky-pylint-shieldsio.json
        label: pylint
        message: ${{ needs.build.outputs.pylint-score }}
        color: green
    - id: shieldsio-coverage
      name: Create the Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.9.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: c7e215b2645a1b63b07f12eff8f13fdb
        filename: taky-coverage-shieldsio.json
        label: coverage
        message: ${{ needs.build.outputs.cov-pct }}
        color: red
